export const TESTIMONIALS = [
  {
    id:       1,
    name:     'Sarah Chen',
    role:     'Head of Data, Stripe',
    quote:    `Prism cut our reporting time by 80%. Our team went from spending full days building dashboards to shipping insights in a couple of hours.`,
    rating:   5,
    initials: 'SC',
    color:    '#114C5A',
  },
  {
    id:       2,
    name:     'Marcus Rodriguez',
    role:     'CTO, Acme Corp',
    quote:    `The AI recommendations paid for itself in the first month. We found a $2 M revenue leak we had absolutely no idea existed.`,
    rating:   5,
    initials: 'MR',
    color:    '#172B36',
  },
  {
    id:       3,
    name:     'Priya Patel',
    role:     'Analytics Lead, Notion',
    quote:    `Best analytics platform we've ever used. The real-time dashboards are incredibly fast and the UX is just chef's kiss.`,
    rating:   5,
    initials: 'PP',
    color:    '#FF9932',
  },
  {
    id:       4,
    name:     'James Whitfield',
    role:     'VP Engineering, Linear',
    quote:    `Switching from our legacy BI stack to Prism was the best decision we made this year. Night and day difference in speed.`,
    rating:   5,
    initials: 'JW',
    color:    '#114C5A',
  },
  {
    id:       5,
    name:     'Aiko Tanaka',
    role:     'Product Manager, Figma',
    quote:    `Prism's collaboration features are unmatched. Every stakeholder now works from the same source of truth — no more spreadsheet chaos.`,
    rating:   5,
    initials: 'AT',
    color:    '#FFC801',
  },
  {
    id:       6,
    name:     'David Osei',
    role:     'Founder, Nomad Labs',
    quote:    `As a startup, we needed a powerful but affordable analytics tool. Prism's Starter plan gave us enterprise-level insights on a bootstrap budget.`,
    rating:   5,
    initials: 'DO',
    color:    '#172B36',
  },
];
